-- Criação da tabela OPM (Unidades/Quarteis)
-- Ajustado para bater com 'opm_rows.sql'
CREATE TABLE IF NOT EXISTS public.opm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GB" TEXT,
    "EB" TEXT,
    "SGB" TEXT,
    municipio_id UUID REFERENCES public.municipalities(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Habilitar RLS
ALTER TABLE public.opm ENABLE ROW LEVEL SECURITY;

-- Permitir leitura para todos os usuários autenticados
CREATE POLICY "Allow public read of opm" ON public.opm
    FOR SELECT USING (auth.role() = 'authenticated');
